### ISSUE TITLE
Program gets stuck in _setupAndRunQueueTimer when a device timeouts

### ISSUE THREAD

**Issue by danielzucchetto** [EatonEM/emcb-udp-coordinator#32]
- emcb-udp-master Version: 0.10.0 (but the problematic code is the same in the current version)
- OS Version: Linux 4.19
- node.js Version: 12.13.0

Steps to Reproduce:

1. Discover devices
2. Change mode of devices to waveform streaming
3. A device timeouts and gets automatically removed by emcb-udp-master

At this point, in the _setupAndRunQueueTimer function, the program gets stuck in the `while(this._messageQueue.length > 0)` cycle, since the message from the timeout device does not satisfy either of the conditions that remove a message from the queue, i.e., `if(this.devices[activeMessage.tx.ipAddress])` (because the device is not in this.devices anymore), and `if(activeMessage.tx.ipAddress === this.ipAddress)`. I expect, instead, the message to be removed from the queue anyway and be discarded.

**Comment by Moneil97** [comment]
I believe this issue is resolved in the latest release (0.12.0). Please re-open if that is not the case
