### ISSUE TITLE
Cannot set property 'activeMessage' of undefined in emcbUDPbroadcastMaster

### ISSUE THREAD

**Issue by deldrid1** [EatonEM/emcb-udp-coordinator#4]
https://github.com/EatonEM/emcb-udp-master/blob/2f2ab61657a18427449c79180e86124d12d21a7a/lib/emcbUDPbroadcastMaster.js#L312

[+   3.178ms]error: uncaughtException: Cannot set property 'activeMessage' of undefined
// TypeError: Cannot set property 'activeMessage' of undefined
// at EmcbUDPbroadcastMaster._setupAndRunQueueTimer (/Users/AustinEldridge/GitRepos/emcb-udp-master/lib/emcbUDPbroadcastMaster.js:312:63)
// at Timeout._messageQueueTimer.setTimeout [as _onTimeout] (/Users/AustinEldridge/GitRepos/emcb-udp-master/lib/emcbUDPbroadcastMaster.js:294:22)
// at ontimeout (timers.js:436:11)
// at tryOnTimeout (timers.js:300:5)
// at listOnTimeout (timers.js:263:5)
/ at Timer.processTimers (timers.js:223:10) {"error":{},"stack":"TypeError: Cannot set property 'activeMessage' of undefined\n    at EmcbUDPbroadcastMaster._setupAndRunQueueTimer (/Users/AustinEldridge/GitRepos/emcb-udp-master/lib/emcbUDPbroadcastMaster.js:312:63)\n    at Timeout._messageQueueTimer.setTimeout [as _onTimeout] (/Users/AustinEldridge/GitRepos/emcb-udp-master/lib/emcbUDPbroadcastMaster.js:294:22)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)","exception":true,"date":"Wed May 22 2019 09:34:54 GMT-0400 (Eastern Daylight Time)","process":{"pid":39103,"uid":501,"gid":20,"cwd":"/Users/AustinEldridge/GitRepos/emcb-beta-imp-firmware","execPath":"/Users/AustinEldridge/.nvm/versions/node/v10.15.3/bin/node","version":"v10.15.3","argv":["/Users/AustinEldridge/.nvm/versions/node/v10.15.3/bin/node","/Users/AustinEldridge/GitRepos/emcb-beta-imp-firmware/lib/UDP/tools/waveformStreaming/server.js"],"memoryUsage":{"rss":45305856,"heapTotal":25190400,"heapUsed":19219496,"external":619482}},"os":{"loadavg":[2.39794921875,1.99169921875,1.9443359375],"uptime":435651},"trace":[{"column":63,"file":"/Users/AustinEldridge/GitRepos/emcb-udp-master/lib/emcbUDPbroadcastMaster.js","function":"EmcbUDPbroadcastMaster._setupAndRunQueueTimer","line":312,"method":"_setupAndRunQueueTimer","native":false},{"column":22,"file":"/Users/AustinEldridge/GitRepos/emcb-udp-master/lib/emcbUDPbroadcastMaster.js","function":"Timeout._messageQueueTimer.setTimeout [as _onTimeout]","line":294,"method":"setTimeout [as _onTimeout]","native":false},{"column":11,"file":"timers.js","function":"ontimeout","line":436,"method":null,"native":false},{"column":5,"file":"timers.js","function":"tryOnTimeout","line":300,"method":null,"native":false},{"column":5,"file":"timers.js","function":"listOnTimeout","line":263,"method":null,"native":false},{"column":10,"file":"timers.js","function":"Timer.processTimers","line":223,"method":"processTimers","native":false}]}

**Comment by Moneil97** [comment]
This section of code was redesigned in the 0.12.0 release, so this line no longer exists.
